WKWebApp/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using WKDomain.Models;
using WKDomain.ModelViews;
using WKWebApp.Manager.Repositories;
using WKWebApp.Models;

namespace WKWebApp.Controllers
{
    [Route("[controller]")]
    public class CategoriaController : Controller
    {
        private readonly ICategoriaRepository _categoriaRepository;

        public CategoriaController(ICategoriaRepository categoriaRepository)
        {
            _categoriaRepository = categoriaRepository;
        }

        [HttpGet("index")]
        public async Task<IActionResult> IndexAsync()
        {
            IEnumerable<Categoria> categoria = await _categoriaRepository.GetAsync();

            return View(categoria);
        }

        [HttpGet("details")]
        public async Task<ActionResult> DetailsAsync(int id)
        {
            var categoria = await _categoriaRepository.GetAsync(id);
            return View(categoria);
        }

        [HttpGet("insert")]
        public async Task<ActionResult> InsertAsync()
        {
            ViewBag.Categorias = await _categoriaRepository.GetAsync();
            return View();
        }

        [HttpPost("insert")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> InsertAsync(NovaCategoria categoria)
        {
            if (!ModelState.IsValid)
                return View(categoria);

            await _categoriaRepository.InsertAsync(categoria);

            TempData["$AlertMessage$"] = "Registro salvo com sucesso!";

            return RedirectToAction("insert");
        }

        [HttpGet("edit")]
        public async Task<ActionResult> EditAsync(int? id)
        {
            if (id == null)
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });

            var categoria = await _categoriaRepository.GetAsync(id.Value);

            if (categoria == null)
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });

            return View(categoria);
        }

        [HttpPost("edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(int id, Categoria categoria)
        {
            if (!ModelState.IsValid)
                return View(categoria);

            if (id != categoria.Id)
                return RedirectToAction(nameof(Error), new { message = "O categoria não corresponde" });

            try
            {
                var result = await _categoriaRepository.UpdateAsync(categoria);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return RedirectToAction(nameof(Error), new { message = e.Message });
            }
        }

        [HttpGet("delete")]
        public async Task<IActionResult> DeleteAsync(int? id)
        {
            if (id != null)
            {
                var obj = await _categoriaRepository.GetAsync(id.Value);

                if (obj != null)
                    return View(obj);
            }

            return RedirectToAction(nameof(Error), new { message = "Id não fornecido" });
        }

        [HttpPost("delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            try
            {
                _categoriaRepository.Delete(id);
            }
            catch (Exception e)
            {
                return RedirectToAction(nameof(Error), new { message = e.Message });
            }

            return RedirectToAction("index");
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };

            return View(viewModel);
        }
    }
}

WKWebApp/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WKDomain.Models;
using WKDomain.ModelViews;
using WKWebApp.Manager.Repositories;
using WKWebApp.Models;

namespace WKWebApp.Controllers
{
    [Route("[controller]")]
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly ICategoriaRepository _categoriaRepository;

        public ProdutoController(IProdutoRepository produtoRepository, ICategoriaRepository categoriaRepository)
        {
            _produtoRepository = produtoRepository;
            _categoriaRepository = categoriaRepository;
        }

        [HttpGet("index")]
        public async Task<IActionResult> IndexAsync()
        {
            IEnumerable<Produto> produto = await _produtoRepository.GetAsync();

            return View(produto);
        }

        [HttpGet("details")]
        public async Task<ActionResult> DetailsAsync(int id)
        {
            var produto = await _produtoRepository.GetAsync(id);
            return View(produto);
        }

        [HttpGet("insert")]
        public IActionResult InsertAsync()
        {
            var categorias = _categoriaRepository.GetAsync().Result;

            ViewBag.Categorias = new SelectList(categorias, "Id", "Nome");

            return View();
        }

        [HttpPost("insert")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InsertAsync(NovoProduto produto)
        {
            if (!ModelState.IsValid)
                return View(produto);

            await _produtoRepository.InsertAsync(produto);

            TempData["$AlertMessage$"] = "Registro salvo com sucesso!";

            return RedirectToAction("Insert");
        }

        [HttpGet("edit")]
        public async Task<IActionResult> EditAsync(int? id)
        {
            if (id == null)
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });

            var produto = await _produtoRepository.GetAsync(id.Value);

            if (produto == null)
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });

            var categorias = _categoriaRepository.GetAsync().Result;

            categorias.Add(new Categoria() { Id = null, Nome = "Selecione uma opção" });

            ViewBag.Categorias = new SelectList(categorias, "Id", "Nome", categorias.Where(x => x.Id == produto.CategoriaId).FirstOrDefault());

            return View(produto);
        }

        [HttpPost("edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync(int id, Produto produto)
        {
            if (!ModelState.IsValid)
                return View(produto);

            if (id != produto.Id)
                return RedirectToAction(nameof(Error), new { message = "O produto não corresponde" });

            try
            {
                var result = await _produtoRepository.UpdateAsync(produto);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return RedirectToAction(nameof(Error), new { message = e.Message });
            }
        }

        [HttpGet("delete")]
        public async Task<IActionResult> DeleteAsync(int? id)
        {
            if (id != null)
            {
                var obj = await _produtoRepository.GetAsync(id.Value);

                if (obj != null)
                    return View(obj);
            }

            return RedirectToAction(nameof(Error), new { message = "Id não fornecido" });
        }

        [HttpPost("delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            try
            {
                _produtoRepository.Delete(id);
            }
            catch (Exception e)
            {
                return RedirectToAction(nameof(Error), new { message = e.Message });
            }

            return RedirectToAction("index");
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };

            return View(viewModel);
        }
    }
}

WKWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WKWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-lux.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Produto" asp-action="Index">WKWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WKWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/scripts/jquery.unobtrusive*"></script>
    <script src="~/scripts/jquery.validate*"></script>
    <script src="~/Scripts/methods_pt.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="~/js/scripts-opw.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "ordering": false,
                "language": {
                    "lengthMenu": "Mostrando _MENU_ registros por página",
                    "zeroRecords": "Nenhum registro encontrado",
                    "info": "Mostrando Página _PAGE_ de _PAGES_",
                    "infoEmpty": "Nenhum registro disponível",
                    "infoFiltered": "(filtrado de _MAX_ registro(s) no total)",
                    "search": "Pesquisar:"
                }
            });
        });
        $(document).ready(function () {
            var table = $('#dataTable').DataTable();

            $('#dataTable_filter label input').on('focus', function () {
                this.setAttribute('id', 'searchInput');
            });
        });
    </script>﻿

    @RenderSection("Scripts", required: false)
</body>
</html>